import Head from 'next/head';
import Link from 'next/link';

const Page1 = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        Page 1 <Link href="/page-2">Go to page 2</Link>
      </main>
    </>
  );
};

Page1.layout = 'layout1';

export default Page1;
