import Head from 'next/head';
import Link from 'next/link';

const Page2 = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        Page 2 <Link href="/page-1">Go to page 1</Link>
      </main>
    </>
  );
};

Page2.layout = 'layout2';

export default Page2;
